[project]
name = "witchculttranslation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kyryl Barabash", email = "kyryl.dev5@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "click>=8.5.0",
    "ebooklib>=0.20",
    "questionary>=2.1.1",
    "requests>=2.34.2",
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "types-requests>=2.33.0.20261006",
]

[project.scripts]
download-rezero-chapter = "witchculttranslation.cli.download_chapter:download_rezero_chapter"
download-rezero-arc = "witchculttranslation.cli.download_arc:download_rezero_arc"
